pipeline {
    agent any

    environment {
        // Safe pointer alias referencing your local secure Jenkins Credentials store entry
        AWS_CREDS = credentials('aws-global-deployer')
    }

    stages {
        stage('Pull Workspace') {
            steps {
                // Pulls down the code updates pushed to GitHub
                checkout scm
            }
        }

        stage('Compile & Lint') {
            steps {
                echo 'Validating python integrity metrics...'
                 dir('aws-ci-cd-jenkins'){
                   sh '''
                    python3 -m venv venv
                    ./venv/bin/pip install -r requirements.txt
                    ./venv/bin/python -m compileall .
                '''
            }
        }
}
        stage('Deploy Live on Host') {
            steps {
                // Secure wrapper injects credentials into the execution block runtime dynamically
                withAWS(credentials: "${AWS_CREDS}", region: 'us-east-1') {
                    echo 'Deploying processes natively to the EC2 host...'
                    
                    // Step into the folder where the venv and application files live
                    dir('aws-ci-cd-jenkins') {
                        sh '''
                            # Stop legacy background instances safely
                            pkill -f "uvicorn app.main:app" || true
                            pkill -f "app.analyzer" || true

                            # Relaunch components natively using nohup background daemons
                            nohup ./venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 > webserver.log 2>&1 &
                            nohup ./venv/bin/python -m app.analyzer > analyzer.log 2>&1 &
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Finished Successfully. No-Docker pipeline is active.'
        }
    }
}
